services:
  - type: web
    name: flutter-python-ai-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # You'll set this manually in Render dashboard
